### ISSUE TITLE
Bug: cursor disappears after float exit

### ISSUE THREAD

**Issue by gipo355** [otavioschwanck/arrow.nvim#48]
After closing the arrow window, cursor disappears

as a starting point i checked up to:

good commit = 0f9b410

bad commit = 591f667

**Comment by gipo355** [comment]
the bad commit is the right one after: ced68e5

**Comment by gipo355** [comment]
lines i believe could cause the issue:

https://github.com/otavioschwanck/arrow.nvim/commit/ced68e5ab9d0bb587cc3eb3a1e542594361d406d#diff-7b671d1540bbdefa9274fa23007c3ca32b804c1e06ae2b64a2c59c2cb1bb0075R544-R545

https://github.com/otavioschwanck/arrow.nvim/commit/ced68e5ab9d0bb587cc3eb3a1e542594361d406d#r141125826

**Comment by rasulomaroff** [comment]
Just checked it and yes it's true, but the interesting part is that before opening a floating window and after closing it you still have the same value for `guicursor` option and it's an empty string.
So, this can be a neovim issue or a specific behaviour. When you don't have a `guicursor` option it seems like you're using a terminal cursor, but if you then append some params to this option, neovim will start using those instead of terminal one. And if you delete those you end up without a cursor at all.

**Comment by rasulomaroff** [comment]
@gipo355 Can you please try it on my branch and check if that works for you?

**Comment by gipo355** [comment]
hey @rasulomaroff can confirm cursor appears

**Comment by otavioschwanck** [comment]
fixed by https://github.com/otavioschwanck/arrow.nvim/commit/37f32c94cf6e01826af5d96337c70d2f9be0a280
